name: Push to Docker Hub

inputs:
  DOCKER_HUB_SECRET:
    required: true
  TAG:
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: dahny
        password: ${{ inputs.DOCKER_HUB_SECRET }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          dahny/${{ github.event.repository.name }}:${{ inputs.TAG }}
          dahny/${{ github.event.repository.name }}:${{ github.sha }}
