name: Deploy to Kubernetes V3

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: false
        default: default
      manifests:
        type: string
        required: false
        default: 'deployment.yaml'
      k8s-url:
        type: string
        required: true
    secrets:
      KUBERNETES_SECRET:
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ inputs.k8s-url }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install kustomize
        working-directory: ${{ inputs.manifests }}
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - name: debug
        working-directory: ${{ inputs.manifests }}
        run: ls && pwd
      - name: edit
        working-directory: ${{ inputs.manifests }}
        run: |
          ./kustomize edit set namespace ${{ inputs.namespace }}
          ./kustomize edit set image dahny/${{ github.event.repository.name }}=dahny/${{ github.event.repository.name }}:${{ github.sha }}
          cat kustomization.yaml
      - name: Apply Kustomize configuration
        working-directory: ${{ inputs.manifests }}
        run: ./kustomize build . | kubectl apply -f -
