name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: false
        default: default
      k8s-url:
        type: string
        required: false
        default: https://99075f78-5058-4466-baab-f7572ff8d4bb.sks-ch-gva-2.exo.io
    secrets:
      KUBERNETES_SECRET:
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ inputs.k8s-url }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: ${{ inputs.namespace }}
          manifests: |
            deployment.yaml
          images: |
            dahny/${{ github.event.repository.name }}:${{ github.sha }}
