name: Build image Graal VM

on:
  workflow_call:
    inputs:
      TAG:
        required: false
        default: latest
        type: string
        description: image tag
      name:
        type: string
    secrets:
      DOCKER_HUB_SECRET:
        required: true
jobs:
  build:
    name: Graal VM build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -Pnative -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName=dahny/${{ github.event.repository.name }}:${{ github.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dahny
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Tag the Docker image
        run: docker tag dahny/${{ github.event.repository.name }}:${{ github.sha }} dahny/${{ github.event.repository.name }}:${{ inputs.TAG }}
      - name: Push
        run: |
          docker push dahny/${{ github.event.repository.name }}:${{ github.sha }}
          docker push dahny/${{ github.event.repository.name }}:${{ inputs.TAG }}