name: Java CI

on:
  workflow_call:
    secrets:
      DOCKER_HUB_SECRET:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dahny
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            dahny/${{ github.event.repository.name }}:latest
            dahny/${{ github.event.repository.name }}:${{ github.sha }}
