name: Java CI

on:
  workflow_call:
    inputs:
      javaVersion:
        type: string
        required: false
        default: '17'
    secrets:
      DOCKER_HUB_SECRET:
        required: true
jobs:
  build:
    name: Maven build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11/17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run my docker push action
        uses: Dahnepfl/actions/.github/actions/docker-push@main
        with:
          DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
          
