name: Node.js CI

on:
  workflow_call:
    secrets:
      DOCKER_HUB_SECRET:
        required: true
        
jobs:
  build:
    name: NPM build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.10.0
          cache: 'npm'
      - id: npm-version
        run: |
          npm pkg get version > out && sed -i 's/"//g' out
          echo "VERSION=$(cat out)" >> $GITHUB_OUTPUT
      - id: npm-version1
        run: |
          echo $GITHUB_OUTPUT
      - id: npm-version2
        run: |
          npm --no-git-tag-version version ${GITHUB_OUTPUT::-2}.$RANDOM
      - run: npm ci
      - run: npm run build --prod
      - run: gzip -k dist/*/*.js
      - run: gzip -k dist/*/*.css
      - run: gzip -k dist/*/*.html
      - name: Run my docker push action
        uses: Dahnepfl/actions/.github/actions/docker-push@main
        with:
          DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
